### ISSUE TITLE
speech output

### ISSUE THREAD

**Issue by pgrandin** [mvglasow/navit#2]
Using ${navigation.item[1].name} you can have navit display the destination item name during a merge, but the speech output does not reflect this.

Example : 
OSD : keep left towards i880 Nimitz Freeway
Speech : now keep left

**Comment by pgrandin** [comment]
Actually i have another example where the speech output was correct.. I need to find the specific place where this did not work as expected.

**Comment by mvglasow** [comment]
For a more theoretical approach, see also https://cs.stackexchange.com/questions/92568/lpa-implementation-keeps-looping (with some more detail on where Navit deviates from the canonical implementations)

**Comment by mvglasow** [comment]
25df0f135 fixes the issue. Three things were amiss in total:

* If traffic distortions changed after creation of the route graph, the corresponding segments were never added to the route graph, so cost changes could never be considered. This required a rewrite of the notification logic (which was due anyway) and now works for added or updated traffic distortions. Deleted distortions are not reflected yet; this still needs to be added.
* In one place in LPA*, I used an incorrect sign for the direction of segments. This is fixed now.
* `route_value_seg()` returns `INT_MAX` if `from` is non-NULL and `from->seg` points to the segment to be evaluated. If `seg` is set for the point being evaluated, the currently shortest path from that segment is considered impassable, and as a result, LPA* will iterate over the entire route graph multiple times until everything is unreachable. Setting `seg` to NULL at the beginning of `route_graph_point_update()` fixes that; it gets set again over the course of the function as a path to the destination is found.

On the simple test case, recalculation now gives me the same result as Dijkstra on a fresh route graph.

Updating the route path does not work yet; exporting the route will still give the old version, although the new one is shown on screen (though I haven’t checked maneuvers yet).
