### ISSUE TITLE
Linguistic issue

### ISSUE THREAD

**Issue by pgrandin** [mvglasow/navit#4]
Using highfive, navit currently says "Turn left now into the <name> street".
A better sentence would be "Turn left now into <name> street".
The trick is that "the" is actually correct for sentences like "Turn left now into the 42nd street".

**Comment by mvglasow** [comment]
Should be fixed now. I would say that "turn left into 42nd Street" or "turn right into 3rd Avenue" is correct usage if that's the street name. However, the article is needed in conjunction with a road number such as M1, D1006 or similar. Fortunately, that is easy to handle: when we have a `name`, omit the article, when we have only a `name_systematic`, include it. The commits of April 2/3 introduce that behavior.
